version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wikimedia
      MYSQL_USER: yourusername
      MYSQL_PASSWORD: yourpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - kafka-network

  zookeeper:
    image: bitnami/zookeeper:3.8.0
    container_name: zookeeper-container
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
    ports:
      - "2181:2181"
    networks:
      - kafka-network

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka-container
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    ports:
      - "9092:9092"
      - "9093:9093"
    depends_on:
      - zookeeper
    networks:
      - kafka-network

  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master-container
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080" # Spark Web UI
      - "7077:7077" # Spark Master Port
      - "4040:4040" # Spark Application UI
    networks:
      - kafka-network
    volumes:
      - ./data:/opt/bitnami/spark/data  # Mount volume for Spark data

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker-container
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master-container:7077
    depends_on:
      - spark-master
    ports:
      - "8081:8081" # Spark Worker UI
    networks:
      - kafka-network
    volumes:
      - ./data:/opt/bitnami/spark/data  # Mount volume for Spark data

networks:
  kafka-network:
    driver: bridge

volumes:
  mysql-data:
  spark-data:  # Define volume for Spark data
